development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: redes_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: redes_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock